Code/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>Type of applicant this is.</description>
        <label>Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <description>Citizenship of the applicant.</description>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <description>Type of the student applying.</description>
        <label>Student Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Traditional</fullName>
                </value>
                <value>
                    <fullName>Adult</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>Type of applicant this requirement applies to.</description>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <description>Citizenship type this requirement applies to.</description>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Citizenship_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hide_Applicant_Type__c</fullName>
        <label>Hide Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hide_Citizenship__c</fullName>
        <label>Hide Citizenship</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Citizenship_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hide_Student_Type__c</fullName>
        <label>Hide Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Name_on_Application__c</fullName>
        <description>Name to display on the application</description>
        <label>Program Name on Application</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <description>Student types this requirement applies to.</description>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code/objects/Question__c.object
<CustomObject>
    <description>Question for a requirement item.</description>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>Type of applicant this question applies to.</description>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <description>Citizenship type(s) this question applies to.</description>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Citizenship_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dependency_Behavior__c</fullName>
        <description>Behavior that occurs when the question dependency logic is performed.</description>
        <label>Dependency Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Hide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dependency_Logic__c</fullName>
        <description>The type of logic performed on the question dependencies.</description>
        <label>Dependency Logic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AND</fullName>
                </value>
                <value>
                    <fullName>OR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Editable_Application_Status__c</fullName>
        <label>Editable Application Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <description>Help text for this question.</description>
        <label>Help Text</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Label for this question.</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <description>Maximum length for this question.</description>
        <label>Length</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picklist_Values__c</fullName>
        <description>List of picklist values, separated by new line.</description>
        <label>Picklist Values</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Placeholder__c</fullName>
        <description>Placeholder text for this question.</description>
        <label>Placeholder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Object_Field__c</fullName>
        <label>Related Object Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <label>Required</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <description>Student Type(s) this question applies to.</description>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <description>Address question.</description>
        <label>Address</label>
    </recordTypes>
    <recordTypes>
        <fullName>Checkbox</fullName>
        <active>true</active>
        <description>Checkbox</description>
        <label>Checkbox</label>
    </recordTypes>
    <recordTypes>
        <fullName>Currency</fullName>
        <active>true</active>
        <description>Currency</description>
        <label>Currency</label>
    </recordTypes>
    <recordTypes>
        <fullName>Date</fullName>
        <active>true</active>
        <description>Date</description>
        <label>Date</label>
    </recordTypes>
    <recordTypes>
        <fullName>DateTime</fullName>
        <active>true</active>
        <description>Date/Time</description>
        <label>Date/Time</label>
    </recordTypes>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <description>Email</description>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>LongTextArea</fullName>
        <active>true</active>
        <description>Text Area (Long)</description>
        <label>Text Area (Long)</label>
    </recordTypes>
    <recordTypes>
        <fullName>MultiPicklist</fullName>
        <active>true</active>
        <description>Picklist (Multi-Select)</description>
        <label>Picklist (Multi-Select)</label>
    </recordTypes>
    <recordTypes>
        <fullName>Percent</fullName>
        <active>true</active>
        <description>Percent</description>
        <label>Percent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <description>Phone</description>
        <label>Phone</label>
    </recordTypes>
    <recordTypes>
        <fullName>Picklist</fullName>
        <active>true</active>
        <description>Picklist</description>
        <label>Picklist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Radio</fullName>
        <active>true</active>
        <description>Radio field</description>
        <label>Radio</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reference</fullName>
        <active>true</active>
        <label>Reference</label>
    </recordTypes>
    <recordTypes>
        <fullName>Static</fullName>
        <active>true</active>
        <label>Static</label>
    </recordTypes>
    <recordTypes>
        <fullName>Text</fullName>
        <active>true</active>
        <description>Text</description>
        <label>Text</label>
    </recordTypes>
    <recordTypes>
        <fullName>TextArea</fullName>
        <active>true</active>
        <description>Text Area</description>
        <label>Text Area</label>
    </recordTypes>
    <recordTypes>
        <fullName>TextEncrypted</fullName>
        <active>true</active>
        <description>Encrypted text field</description>
        <label>Text (Encrypted)</label>
    </recordTypes>
    <recordTypes>
        <fullName>URL</fullName>
        <active>true</active>
        <description>URL</description>
        <label>URL</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Code/objects/Question_Dependency__c.object
<CustomObject>
    <fields>
        <fullName>Controlling_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Question that controls this dependency.</description>
        <label>Controlling Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Dependent Questions</relationshipLabel>
        <relationshipName>Question_Dependencies1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question that is dependent on this dependency.</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Dependencies</relationshipLabel>
        <relationshipName>Question_Dependencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ValueCheckbox__c</fullName>
        <description>Checkbox value that the controlling question has to equal.</description>
        <label>Value</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>True</fullName>
                    <default>true</default>
                    <label>True</label>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value that the controlling question has to be.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Dependency</label>
    <nameField>
        <displayFormat>QD-{000000}</displayFormat>
        <label>Question Dependency Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Dependencies</pluralLabel>
    <recordTypes>
        <fullName>Checkbox</fullName>
        <active>true</active>
        <description>Checkbox question dependency.</description>
        <label>Checkbox</label>
    </recordTypes>
    <recordTypes>
        <fullName>Multi_Select_Picklist</fullName>
        <active>true</active>
        <description>Multi-Select picklist question dependency.</description>
        <label>Multi-Select Picklist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Picklist</fullName>
        <active>true</active>
        <description>Picklist question dependency.</description>
        <label>Picklist</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Code/objects/Question_Response__c.object
<CustomObject>
    <description>Junction object between requirement response and question.</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country value for address fields.</description>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPopulated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPopulated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsRequired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsShown__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsShown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Question that this response is for.</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement_Response__c</fullName>
        <description>Requirement response this question response is for.</description>
        <label>Requirement Response</label>
        <referenceTo>Requirement_Response__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State value for address fields.</description>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValueCheckbox__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox value.</description>
        <label>Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValuePhone__c</fullName>
        <description>Phone value of this response.</description>
        <label>Value</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ValueText__c</fullName>
        <description>Text value for this response.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000000}</displayFormat>
        <label>Question Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Code/objects/Requirement_Response__c.object
<CustomObject>
    <description>Junction object between requirement and application.</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>Application this response is for.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Requirement Responses</relationshipLabel>
        <relationshipName>Requirement_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement Response</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Requirement Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirement Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Applicant_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <description>Types of an applicant.</description>
    <masterLabel>Applicant Types</masterLabel>
</GlobalValueSet>

Code/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

Code/globalValueSets/Citizenship_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Domestic</fullName>
    </customValue>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <description>Citizenship types for admissions.</description>
    <masterLabel>Citizenship Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Student_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Traditional</fullName>
    </customValue>
    <customValue>
        <fullName>Adult</fullName>
    </customValue>
    <description>Student types for admissions.</description>
    <masterLabel>Student Types</masterLabel>
</GlobalValueSet>

Code/classes/ApplicationQuestion.cls
/*******************************************************************************
@description This class controls the visibility and behavior of Questions
@author Huron Consulting Group

Revision (s): 
*******************************************************************************/
public class ApplicationQuestion {

    public static final Map<Schema.DisplayType, String> fieldTypes = new Map<Schema.DisplayType, String> {
        Schema.DisplayType.ADDRESS => 'Address',
        Schema.DisplayType.BOOLEAN => 'Checkbox',
        Schema.DisplayType.CURRENCY => 'Currency',
        Schema.DisplayType.DATE => 'Date',
        Schema.DisplayType.DATETIME => 'DateTime',
        Schema.DisplayType.DOUBLE => 'Decimal',
        Schema.DisplayType.EMAIL => 'Email',
        Schema.DisplayType.ENCRYPTEDSTRING => 'TextEncrypted',
        Schema.DisplayType.INTEGER => 'Integer',
        Schema.DisplayType.MULTIPICKLIST => 'MultiPicklist',
        Schema.DisplayType.PERCENT => 'Percent',
        Schema.DisplayType.PHONE => 'Phone',
        Schema.DisplayType.PICKLIST => 'Picklist',
        Schema.DisplayType.REFERENCE => 'Reference',
        Schema.DisplayType.STRING => 'Text',
        Schema.DisplayType.TEXTAREA => 'TextArea',
        Schema.DisplayType.URL => 'URL'
    };

    public String fieldType { get { return tableBased ? question.RecordType.DeveloperName : fieldTypes.get(displayType); } }

    public String label {get;private set;}
    public sObject obj {get;set;}
    public  String fieldName {get;set;}
    public String value;
    public Boolean checkboxValue;
    public Decimal decimalValue;
    public Datetime datetimeValue;
    public Date dateValue;
    public Integer integerValue;
    public String placeholder {get;private set;}
    public Integer length {get;set;}
    public Schema.DisplayType displayType {get;set;}
    public Contact con {get;set;}
    public Account acc {get;set;}
    public Boolean placeholderQuestion{get;set;}
    public Object resp{get;set;}
    private Requirement_Response__c reqResponse;
    /*******************************************************************************
    * @description Returns the list of selct options for picklists/multiselect picklists and radios. For Intended Programs we also filter out programs that should not be shown.
    ********************************************************************************/
    public List<SelectOption> options {
        get { 
            if(intendedPrograms != null){
                options = new List<SelectOption>();
                options.add(new SelectOption('','--None--'));
                for(Program__c ip : intendedPrograms){
                    if(showIntendedProgram(ip)){
                        options.add(new SelectOption(ip.Id,(String.isNotBlank(ip.Program_Name_on_Application__c)?ip.Program_Name_on_Application__c:ip.Name)));
                    }
                }
                return options;
            }else if (dependentOptions == null){
                return options;
            }
            return dependentOptions.get(controllingQuestion.response.ValueText__c);
    	}
        private set;
    }

    public List<String> multiPicklistValues;
    public Question__c question {get;set;}
    private Boolean tableBased {get;set;}
    public Question_Response__c response {get;set;}
    public String helpText {get;set;}

    public Application__c application {get;set;}
    public ApplicationQuestion controllingQuestion {get;set;}
    public List<SObject> filteringValues;
    public String filteringLabel;
    public String filteringValue;
    public Map<ApplicationQuestion,Set<String>> multiControllingQuestions;
    public List<Program__c> intendedPrograms;
    public Set<String> showValues {get;set;}
    public Map<String, List<SelectOption>> dependentOptions {get;set;}
    public Boolean radio {get;set;}
    public List<Question_Dependency__c> dQuestions {get;set;}
    public Map<Id, ApplicationQuestion> controllingQuestions {get;set;}

    public static Boolean stateAndCountryPicklistEnabled = false;
    public static Boolean getStateAndCountryPicklistEnabled(){return stateAndCountryPicklistEnabled;}
    static{
        Map<String, Schema.SObjectField> accountFields = Account.sObjectType.getDescribe().fields.getMap();
		stateAndCountryPicklistEnabled = accountFields.containsKey('BillingCountryCode');
    }

    private Boolean forceShowQuestion = false;
    public Boolean showRelatedLabel{get;private set;}

    /*******************************************************************************
    * @description Determines if this question is editable based on the application status
    ********************************************************************************/
    public Boolean isEditable{
        get{
            if(UserInfo.getUserType() != 'Standard'){
                if(application != null && String.isNotBlank(application.Application_Status__c)){
                    if(question != null && (String.isBlank(question.Editable_Application_Status__c) || (String.isNotBlank(question.Editable_Application_Status__c) && new Set<String>(question.Editable_Application_Status__c.split(';')).contains(application.Application_Status__c)))){
                        return true;
                    }
                    return false;
                }
            }
            return true;
        }
    }

    /*******************************************************************************
    * @description calculates if this specific program should be shown
    ********************************************************************************/
    public Boolean showIntendedProgram(Program__c ip){
        if (String.isNotBlank(ip.Hide_Applicant_Type__c) && (String.isNotBlank(application.Applicant_Type__c) && (new Set<String>(ip.Hide_Applicant_Type__c.split(';'))).contains(application.Applicant_Type__c)))
            return false;

        if (String.isNotBlank(ip.Hide_Citizenship__c) && (String.isNotBlank(application.Citizenship__c) && (new Set<String>(ip.Hide_Citizenship__c.split(';'))).contains(application.Citizenship__c)))
            return false;

        if (String.isNotBlank(ip.Hide_Student_Type__c) && (String.isNotBlank(application.Student_Type__c) && (new Set<String>(ip.Hide_Student_Type__c.split(';'))).contains(application.Student_Type__c)))
            return false;

        return true;
    }
    /*******************************************************************************
    * @description checks the answer to multiple questions to decide if a dependent question should be shown
    ********************************************************************************/
    public Boolean checkMultiControllingQuestion(){
        Boolean retValue = true;
        if(multiControllingQuestions != null){
            for(ApplicationQuestion aq : multiControllingQuestions.keySet()){
                if(aq.response == null || String.isBlank(aq.response.ValueText__c) || !multiControllingQuestions.get(aq).contains(aq.response.ValueText__c)){
                    retValue = false;
                }
            }
        }
        return retValue;
    }

    /*******************************************************************************
    * @description Calculates whether to render the question or not
    ********************************************************************************/
    public Boolean showQuestion {
        get {
            if(obj!=null && String.isNotBlank(fieldName) && response != null && fieldType != fieldTypes.get(Schema.DisplayType.ADDRESS)){
                obj.put(fieldName,response.ValueText__c);
            }
            if(forceShowQuestion == true){
                return true;
            }
            if(application != null && question != null && !ApplicationFilter.filter(application,question)){
                return false;
            }
            //Are the answers to controlling questions the right answer to render this question
            if (!tableBased){
                return (controllingQuestion == null && multiControllingQuestions == null) || ( controllingQuestion != null && String.isNotBlank(controllingQuestion.response.ValueText__c) && showValues.contains(controllingQuestion.response.ValueText__c) || (multiControllingQuestions != null && checkMultiControllingQuestion()));
            }
            if (dQuestions == null || controllingQuestions == null || dQuestions.isEmpty() || controllingQuestions.isEmpty())
                return true;
            //Based on Question_Dependency records, should this question be shown.
            if (String.isBlank(question.Dependency_Logic__c) || question.Dependency_Logic__c.equals('AND')) {
                for (Question_Dependency__c qd:dQuestions) {
                    if (controllingQuestions.containsKey(qd.Controlling_Question__c))
                        if (qd.RecordType.DeveloperName.equals('Checkbox') && controllingQuestions.get(qd.Controlling_Question__c).response != null && Boolean.valueOf(qd.ValueCheckbox__c) != controllingQuestions.get(qd.Controlling_Question__c).response.ValueCheckbox__c){
                            return String.isNotBlank(question.Dependency_Behavior__c) && question.Dependency_Behavior__c.equals('Hide');
                        }else if (qd.RecordType.DeveloperName.equals('Picklist') && (String.isBlank(controllingQuestions.get(qd.Controlling_Question__c).response.ValueText__c) || !qd.Value__c.equals(controllingQuestions.get(qd.Controlling_Question__c).response.ValueText__c)))
                        	return String.isNotBlank(question.Dependency_Behavior__c) && question.Dependency_Behavior__c.equals('Hide');
                        else if (qd.RecordType.DeveloperName.equals('Multi_Select_Picklist')){
                            if(String.isNotBlank(controllingQuestions.get(qd.Controlling_Question__c).response.ValueText__c) && String.isNotBlank(qd.Value__c)){
                                Set<String> multiItems = new Set<String>(controllingQuestions.get(qd.Controlling_Question__c).response.ValueText__c.split(';'));
                                Boolean foundValue = false;
                                for(String controlItem : qd.Value__c.split(';')){
                                    if(multiItems.contains(controlItem)){
                                        foundValue = true;
                                        break;
                                    }
                                }
                                if(!foundValue){
                                    return String.isNotBlank(question.Dependency_Behavior__c) && question.Dependency_Behavior__c.equals('Hide');
                                }
                            }else{
                                return String.isNotBlank(question.Dependency_Behavior__c) && question.Dependency_Behavior__c.equals('Hide');
                            }
                        }
                }
                return String.isBlank(question.Dependency_Behavior__c) || question.Dependency_Behavior__c.equals('Show');
            } else {
                for (Question_Dependency__c qd:dQuestions) {
                    if (!controllingQuestions.containsKey(qd.Controlling_Question__c))
                        return String.isBlank(question.Dependency_Behavior__c) || question.Dependency_Behavior__c.equals('Show');
                    else if (qd.RecordType.DeveloperName.equals('Checkbox') && Boolean.valueOf(qd.ValueCheckbox__c) == controllingQuestions.get(qd.Controlling_Question__c).response.ValueCheckbox__c)
                        return String.isBlank(question.Dependency_Behavior__c) || question.Dependency_Behavior__c.equals('Show');
                    else if (qd.RecordType.DeveloperName.equals('Picklist') && String.isNotBlank(controllingQuestions.get(qd.Controlling_Question__c).response.ValueText__c) && qd.Value__c.equals(controllingQuestions.get(qd.Controlling_Question__c).response.ValueText__c))
                        return String.isBlank(question.Dependency_Behavior__c) || question.Dependency_Behavior__c.equals('Show');
                    else if (qd.RecordType.DeveloperName.equals('Multi_Select_Picklist')){
                        if(String.isNotBlank(controllingQuestions.get(qd.Controlling_Question__c).response.ValueText__c) && String.isNotBlank(qd.Value__c)){
                            Set<String> multiItems = new Set<String>(controllingQuestions.get(qd.Controlling_Question__c).response.ValueText__c.split(';'));
                            Boolean foundValue = false;
                            for(String controlItem : qd.Value__c.split(';')){
                                if(multiItems.contains(controlItem)){
                                    foundValue = true;
                                    break;
                                }
                            }
                            if(foundValue){
                                return String.isBlank(question.Dependency_Behavior__c) || question.Dependency_Behavior__c.equals('Show');
                            }
                        }
                    }
                }
                return String.isNotBlank(question.Dependency_Behavior__c) && question.Dependency_Behavior__c.equals('Hide');
            }
        }
    }

    public ApplicationQuestion(Schema.FieldSetMember fsm, SObject obj, Schema.SObjectType objType){
        question = new Question__c(Related_Object_Field__c=fsm.getFieldPath(), Label__c = fsm.getLabel());
        this.con = new Contact();
        label = question.Label__c;
        this.displayType = fsm.getType();
        this.obj = obj;
        forceShowQuestion = true;
        showRelatedLabel = true;
        tableBased = false;
        if(!fsm.getFieldPath().contains('.')){
            Schema.DescribeFieldResult dfr = objType.getDescribe().fields.getMap().get(fsm.getFieldPath().toLowerCase()).getDescribe();
            if (displayType == Schema.DisplayType.PICKLIST) {
                options = new List<SelectOption>{new SelectOption('', '--None--')};
                for (Schema.PicklistEntry ple:dfr.getPicklistValues())
                    options.add(new SelectOption(ple.getValue(), ple.getLabel()));
            }

            if (displayType == Schema.DisplayType.MULTIPICKLIST) {
                options = new List<SelectOption>();
                for (Schema.PicklistEntry ple:dfr.getPicklistValues())
                    options.add(new SelectOption(ple.getValue(), ple.getLabel()));
            }
        }
    }
    public ApplicationQuestion(SObject obj, Question__c question, Question_Response__c response) {
        if(obj.getSObjectType() == Application__c.sObjectType){
            this.application = (Application__c)obj;
        }else{
            this.obj = obj;
        }
        this.question = question;
        this.tableBased = true;
        if(obj == null){
            this.obj = response;
        }
        this.response = response;

        //this.fieldName = fieldNames.get(question.RecordType.DeveloperName);
        if (question.Length__c == null || (question.Length__c > 255 && !fieldType.equals('LongTextArea')))
            this.length = 255;
        else
            this.length = (Integer)question.Length__c;

        this.placeholder = question.Placeholder__c;

        this.label = question.Label__c;

        this.helpText = question.Help_Text__c;
        this.con = new Contact();
        if(String.isNotBlank(fieldType)){
            if (fieldType.contains('Picklist') || fieldType.equals('Radio')) {
                options = new List<SelectOption>();
                if (fieldType.equals('Picklist')) options.add(new SelectOption('', '--None--'));
                if(String.isNotBlank(question.Picklist_Values__c)){
                    for (String str:question.Picklist_Values__c.split('\n')){
                        options.add(new SelectOption(str.trim(), str.trim()));
                    }
                }
            }
            if (fieldType.equals('Address') && this.response != null) {
                if(stateAndCountryPicklistEnabled == true){
                    this.con.put('MailingStateCode', this.response.State__c);
                    this.con.put('MailingCountryCode', this.response.Country__c);
                }else{
                    this.con.put('MailingState', this.response.State__c);
                    this.con.put('MailingCountry', this.response.Country__c);
                }
            }
        }
    }
    public ApplicationQuestion(Application__c app, String label, sObject obj, String fieldName, Schema.DisplayType displayType, Boolean placeholderQuestion) {
        init(label, obj, fieldName, '',displayType);
        this.application = app;
        this.placeholderQuestion = placeholderQuestion;
    }
    public ApplicationQuestion(Application__c app, String label, sObject obj, String fieldName) {
        init(label, obj, fieldName, '',null);
        this.application = app;
    }

    public ApplicationQuestion(Application__c app, String label, sObject obj, String fieldName, String placeholder) {
        init(label, obj, fieldName, placeholder,null);
        this.application = app;
    }
    /*******************************************************************************
    * @description Sets up the question based on the input object and display type
    ********************************************************************************/
    private void init(String label, sObject obj, String fieldName, String placeholder, Schema.DisplayType dType) {
        this.tableBased = false;

        this.label = label;
        this.obj = obj;
        this.fieldName = fieldName;
        this.placeholder = placeholder;
        this.con = new Contact();
        this.response = new Question_Response__c();
        Schema.DescribeFieldResult dfr = obj.getSObjectType().getDescribe().fields.getMap().get(fieldName).getDescribe();
        if(dType == null){
            displayType = dfr.getType();
            this.length = dfr.getLength();
        }else{
            displayType = dType;
        }

        if (displayType == Schema.DisplayType.PICKLIST) {
            options = new List<SelectOption>{new SelectOption('', '--None--')};
            for (Schema.PicklistEntry ple:dfr.getPicklistValues())
                options.add(new SelectOption(ple.getValue(), ple.getLabel()));
        }

        if (displayType == Schema.DisplayType.MULTIPICKLIST) {
            options = new List<SelectOption>();
            for (Schema.PicklistEntry ple:dfr.getPicklistValues())
                options.add(new SelectOption(ple.getValue(), ple.getLabel()));
        }
    }
    /*******************************************************************************
    * @description Should we render this question's label
    ********************************************************************************/
    public void showRelatedLabel(Boolean showLabel){
        showRelatedLabel = showLabel;
    }
    /*******************************************************************************
    * @description Sets the picklist options for this question
    ********************************************************************************/
    public void setPicklistOptions(Map<String, String> options) {
        this.options = new List<SelectOption>{new SelectOption('', '--None--')};
        for (String k:options.keySet())
            this.options.add(new SelectOption(k, options.get(k)));
    }
    /*******************************************************************************
    * @description Sets the picklist options based on a lookup field
    ********************************************************************************/
    public void setReferenceOptions(Map<Id, String> refOptions) {
        this.options = new List<SelectOption>{new SelectOption('', '--None--')};
        for (Id k:refOptions.keySet())
            this.options.add(new SelectOption(String.valueOf(k), refOptions.get(k)));
    }
    /*******************************************************************************
    * @description Sets which question controls the rendering of this question
    ********************************************************************************/
    public void addControllingQuestion(ApplicationQuestion controllingQuestion, Set<String> showValues) {
        this.controllingQuestion = controllingQuestion;
        this.showValues = showValues;
    }
    /*******************************************************************************
    * @description Sets which questions controls the rendering of this question
    ********************************************************************************/
    public void addControllingQuestions(Map<ApplicationQuestion,Set<String>> controllingQuestions) {
        this.multiControllingQuestions = controllingQuestions;
    }
    /*******************************************************************************
    * @description Set up the list of question dependencies to control the rendering of this question
    ********************************************************************************/
    public void addQuestionDependencies(List<Question_Dependency__c> dQuestions, Map<Id, ApplicationQuestion> controllingQuestions) {
        this.dQuestions = dQuestions;
        this.controllingQuestions = controllingQuestions;
    }

    /*******************************************************************************
    * @description Set up the list of dependency options in the form of a map to determine the rendering of this question
    ********************************************************************************/
    public void addDependentOptions(Map<String, Map<String, String>> depOptions) {
        this.dependentOptions = new Map<String, List<SelectOption>>();
        for (String k:depOptions.keySet()) {
            List<SelectOption> ops = new List<SelectOption>{new SelectOption('', '--None--')};
            for (String dk:depOptions.get(k).keySet()){
                if(depOptions.get(k).get(dk) != null){
                ops.add(new SelectOption(dk, depOptions.get(k).get(dk)));
                }
            }
            this.dependentOptions.put(k, ops);
        }
    }
    /*******************************************************************************
    * @description Add the list of all Program records
    ********************************************************************************/
    public void addIntendedProgramFilteringList(List<Program__c> intendedPrograms){
        this.intendedPrograms = intendedPrograms;
    }
    /*******************************************************************************
    * @description Turns a picklist field into a radio
    ********************************************************************************/
    public void makeRadio() {
        this.options.remove(0);
        this.radio = true;
    }

    /*******************************************************************************
    * @description Find the relevant response value and prepares the question response to be saved
    ********************************************************************************/
    public void processValue() {
        if(response != null){
            if (fieldType.equals('Address')) {
                if(stateAndCountryPicklistEnabled == true){
                    response.State__c = (String)con.get('MailingStateCode');
                    response.Country__c = (String)con.get('MailingCountryCode');
                }else{
                    response.State__c = (String)con.get('MailingState');
                    response.Country__c = (String)con.get('MailingCountry');
                }
            }
            response.IsShown__c = showQuestion;
            if(question!=null){
                response.IsRequired__c = (application != null && String.isNotBlank(question.Required__c) && new Set<String>(question.Required__c.split(';')).contains(application.Application_Status__c));
            }
            response.IsPopulated__c = false;
            if(String.isNotBlank(response.ValueText__c) || (question != null && question.RecordType.DeveloperName == 'Checkbox') || String.isNotBlank(response.ValuePhone__c) || String.isNotBlank(response.ValueEmail__c) || response.ValueCurrency__c != null ||
                response.ValueDate__c != null || response.ValueDateTime__c != null || response.ValueNumber__c != null || response.ValuePercent__c != null || String.isNotBlank(response.ValueTextArea__c) ||
                    String.isNotBlank(response.ValueLongTextArea__c) || String.isNotBlank(response.ValueURL__c) || String.isNotBlank(response.ValueTextEncrypted__c) || (String.isNotBlank(response.Street__c) && String.isNotBlank(response.State__c) && String.isNotBlank(response.City__c) && String.isNotBlank(response.Country__c) && String.isNotBlank(response.PostalCode__c))){
                        response.IsPopulated__c = true;
            }
            if(String.isNotBlank(response.ValueText__c)){
                resp = response.ValueText__c;
            }
            if(displayType == Schema.DisplayType.BOOLEAN){
                resp = response.ValueCheckbox__c?response.ValueCheckbox__c:false;
            }
            if(String.isNotBlank(response.ValuePhone__c)){
                resp = response.ValuePhone__c;
            }
            if(String.isNotBlank(response.ValueEmail__c)){
                resp = response.ValueEmail__c;
            }
            if(response.ValueCurrency__c != null){
                resp = response.ValueCurrency__c;
            }
            if(response.ValueDate__c != null){
                resp = response.ValueDate__c;
            }
            if(response.ValueDateTime__c != null){
                resp = response.ValueDateTime__c;
            }
            if(response.ValueNumber__c != null){
                resp = response.ValueNumber__c;
            }
            if(response.ValuePercent__c != null){
                resp = response.ValuePercent__c;
            }
            if(String.isNotBlank(response.ValueTextArea__c)){
                resp = response.ValueTextArea__c;
            }
            if(String.isNotBlank(response.ValueLongTextArea__c)){
                resp = response.ValueLongTextArea__c;
            }
            if(String.isNotBlank(response.ValueURL__c)){
                resp = response.ValueURL__c;
            }
            if(String.isNotBlank(response.ValueTextEncrypted__c)){
                resp = response.ValueTextEncrypted__c;
            }
        }
    }
    /*******************************************************************************
    * @description Set the Requirement Response for this Application Question
    ********************************************************************************/
    public void setRequirementResponse(Requirement_Response__c reqResponse){
        this.reqResponse = reqResponse;
    }
    /*******************************************************************************
    * @description Send a reminder email for Exteral Requirements
    ********************************************************************************/
    public void sendReminder(){
        system.debug('SENDREMINDER');
        system.debug(question);
        system.debug(reqResponse);
        if(question != null && question.External_EmaiL_Field__c == true && reqResponse != null && String.isNotBlank(reqResponse.External_Email__c) && reqResponse.Id != null){
            update new Requirement_Response__c(Id=reqResponse.Id, Send_Reminder__c = !reqResponse.Send_Reminder__c);
        }
    }
    public Datetime getDatetimeValue() {
        return response.ValueDateTime__c;
    }

    public void setDatetimeValue(Datetime v) {
        response.ValueDateTime__c = v;
    }

    public Date getDateValue() {
        return response.ValueDate__c;
    }

    public void setDateValue(Date v) {
        response.ValueDate__c = v;
    }

    public List<String> getMultiPicklistValues() {
        return String.isNotBlank(response.ValueText__c) ? response.ValueText__c.split(';') : new List<String>();
    }

    public void setMultiPicklistValues(List<String> v) {
        response.ValueText__c = String.join(v, ';');
    }
}