src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>Activate_Application_Date__c</fullName>
        <inlineHelpText>Date in which applications for this term open.</inlineHelpText>
        <label>Activate Application Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Application_Date__c</fullName>
        <inlineHelpText>Date in which applications for this term close.</inlineHelpText>
        <label>End Application Date</label>
        <type>Date</type>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Control__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this Application Control is currently active for applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Cancel_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Cancel&quot; button shows-up for.</inlineHelpText>
        <label>Allow Cancel From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Allow_Submit_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Submit&quot; button shows-up for.</inlineHelpText>
        <label>Allow Submit From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Allow_Withdraw_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Withdraw&quot; button shows-up for.</inlineHelpText>
        <label>Allow Withdraw From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Start_Status__c</fullName>
        <inlineHelpText>Application status that new applications are set to.</inlineHelpText>
        <label>Application Start Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancel_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Cancel&quot; button sets an application to</inlineHelpText>
        <label>Cancel Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this is the default Application Control when no URL Parameter is specified</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submit_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Submit&quot; button sets an application to</inlineHelpText>
        <label>Submit Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL_Parameter__c</fullName>
        <inlineHelpText>Text to be included at the end of a link to reference this Application Control. Format is &quot;?at=[URL_PARAMETER]&quot;</inlineHelpText>
        <label>URL Parameter</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Withdraw_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Withdraw&quot; button sets an application to</inlineHelpText>
        <label>Withdraw Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Application Control</label>
    <nameField>
        <label>Application Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked if this program is currently active. Unchecked otherwise.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Question for a requirement item.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this question is active. If unchecked, this question won&apos;t display on any applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Intended Program this question applies to (applies to all if blank)</inlineHelpText>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement_Item__c</fullName>
        <inlineHelpText>Requirement item for this question</inlineHelpText>
        <label>Requirement Item</label>
        <referenceTo>Requirement_Item__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>URL_Parameter__c</fullName>
        <description>The URL Parameter to be used as a key when pre-populating this question</description>
        <label>URL Parameter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <description>Address question.</description>
        <label>Address</label>
    </recordTypes>
    <recordTypes>
        <fullName>Checkbox</fullName>
        <active>true</active>
        <description>Checkbox</description>
        <label>Checkbox</label>
    </recordTypes>
    <recordTypes>
        <fullName>Currency</fullName>
        <active>true</active>
        <description>Currency</description>
        <label>Currency</label>
    </recordTypes>
    <recordTypes>
        <fullName>Date</fullName>
        <active>true</active>
        <description>Date</description>
        <label>Date</label>
    </recordTypes>
    <recordTypes>
        <fullName>DateTime</fullName>
        <active>true</active>
        <description>Date/Time</description>
        <label>Date/Time</label>
    </recordTypes>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <description>Email</description>
        <label>Email</label>
    </recordTypes>
    <recordTypes>
        <fullName>LongTextArea</fullName>
        <active>true</active>
        <description>Text Area (Long)</description>
        <label>Text Area (Long)</label>
    </recordTypes>
    <recordTypes>
        <fullName>MultiPicklist</fullName>
        <active>true</active>
        <description>Picklist (Multi-Select)</description>
        <label>Picklist (Multi-Select)</label>
    </recordTypes>
    <recordTypes>
        <fullName>Number</fullName>
        <active>true</active>
        <description>Number</description>
        <label>Number</label>
    </recordTypes>
    <recordTypes>
        <fullName>Percent</fullName>
        <active>true</active>
        <description>Percent</description>
        <label>Percent</label>
    </recordTypes>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <description>Phone</description>
        <label>Phone</label>
    </recordTypes>
    <recordTypes>
        <fullName>Picklist</fullName>
        <active>true</active>
        <description>Picklist</description>
        <label>Picklist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reference</fullName>
        <active>true</active>
        <label>Reference</label>
    </recordTypes>
    <recordTypes>
        <fullName>Static</fullName>
        <active>true</active>
        <label>Static</label>
    </recordTypes>
    <recordTypes>
        <fullName>Text</fullName>
        <active>true</active>
        <description>Text</description>
        <label>Text</label>
    </recordTypes>
    <recordTypes>
        <fullName>TextArea</fullName>
        <active>true</active>
        <description>Text Area</description>
        <label>Text Area</label>
    </recordTypes>
    <recordTypes>
        <fullName>TextEncrypted</fullName>
        <active>true</active>
        <description>Encrypted text field</description>
        <label>Text (Encrypted)</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if the requirement is active. If unchecked, this requirement will not display on any applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application_Control__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Application Control that this requirement is a part of</inlineHelpText>
        <label>Application Control</label>
        <referenceTo>Application_Control__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Intended program that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_on_Application_Creation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this requirement should display when creating a new application and not on the checklist</inlineHelpText>
        <label>Show on Application Creation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>URL_Parameter__c</fullName>
        <formula>Application_Control__r.URL_Parameter__c</formula>
        <label>URL Parameter</label>
        <type>Text</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Requirement_Item__c.object
<CustomObject>
    <description>An item that&apos;s part of an admissions requirement.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked if this requirement item is active. If unchecked, it will not display on any applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Intended Program that this requirement item applies to (applies to all if blank)</inlineHelpText>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Requirement Items</relationshipLabel>
        <relationshipName>Requirement_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <inlineHelpText>Requirement that this item is a part of</inlineHelpText>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Requirement Items</relationshipLabel>
        <relationshipName>Requirement_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement Item</label>
    <nameField>
        <label>Requirement Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirement Items</pluralLabel>
    <recordTypes>
        <fullName>Question_Group</fullName>
        <active>true</active>
        <description>Group of questions.</description>
        <label>Question Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

src/classes/ApplicationRegistrationTest.cls
@isTest
public class ApplicationRegistrationTest {
	@testSetup
	public static void testSetup(){
        Application_Control__c appControl = new Application_Control__c(
            Application_Start_Status__c=Application_Control__c.Application_Start_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Active__c=true,
            Allow_Cancel_From__c=Application_Control__c.Allow_Cancel_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Allow_Withdraw_From__c=Application_Control__c.Allow_Withdraw_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Allow_Submit_From__c=Application_Control__c.Allow_Submit_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Cancel_Status__c=Application_Control__c.Cancel_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Default__c=true,
            URL_Parameter__c ='st',
            Submit_Status__c=Application_Control__c.Submit_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Withdraw_Status__c=Application_Control__c.Withdraw_Status__c.getDescribe().getPicklistValues()[0].getValue()
        );
        insert appControl;
        
		Account acc = new Account(Name='Test School');
		insert acc;

		insert new Program__c(Name='Test',Active__c=true);


		Map<String,Id> rtMap = new Map<String,Id>();
		for(RecordType rt : [Select Id,DeveloperName from RecordType where sObjectType = 'Requirement_Item__c']){
			rtMap.put(rt.DeveloperName,rt.Id);
		}

		Map<String,Id> rtQMap = new Map<String,Id>();
		for(RecordType rt : [Select Id,DeveloperName from RecordType where sObjectType = 'Question__c']){
			rtQMap.put(rt.DeveloperName,rt.Id);
		}

		Requirement__c req = new Requirement__c(Application_Control__c=appControl.Id,Active__c = true,Name='Test Req',Show_on_Application_Creation__c=true);
		insert req;
		Requirement_Item__c riQG = new Requirement_Item__c(Requirement__c=req.Id,Name='Test RI',Active__c = true,RecordTypeId=rtMap.get('Question_Group'));
		insert riQG;
		insert new Question__c(Requirement_Item__c=riQG.Id,Name='Test',RecordTypeId=rtQMap.get('Text'));

		insert new Program__c(Name='Test');
		insert new Academic_Term__c(Activate_Application_Date__c=Date.today().addDays(-2),End_Application_Date__c=Date.today().addDays(2));
	}
	public static TestMethod void testCreate(){
		Account acc = [Select Id from Account limit 1];
		Program__c ap = [Select id from Program__c limit 1];
		Academic_Term__c at = [Select id from Academic_Term__c limit 1];

		PageReference pr = Page.ApplicationRegistration;
		Test.setCurrentPage(pr);
		ApplicationRegistration ac = new ApplicationRegistration();

		for(ApplicationQuestionGroup aqg : ac.section.groups){
            for(ApplicationQuestion question : aqg.questions){
				List<SelectOption> options = question.options;
				Boolean isShown = question.showQuestion;
				
                if(String.isNotBlank(question.fieldName) && question.response != null){
					if(question.fieldType == 'Address'){
						question.response.Street__c = 'test street';
						question.response.City__c = 'test city';
						if(ApplicationQuestion.stateAndCountryPicklistEnabled == true){
							question.con.put('MailingCountryCode', 'US');
							question.con.put('MailingStateCode', 'AL');
						}else{
							question.con.put('MailingCountry', 'US');
							question.con.put('MailingState', 'AL');
						}
						question.response.PostalCode__c = '12345';
					}else if(question.fieldType == 'Checkbox'){
						question.response.ValueCheckbox__c = true;
					}else if(question.fieldType == 'Currency'){
						question.response.ValueCurrency__c = 100.23;
					}else if(question.fieldType == 'Date'){
						question.response.ValueDate__c = Date.today();
					}else if(question.fieldType == 'DateTime'){
						question.response.ValueDateTime__c = Datetime.now();
					}else if(question.fieldType == 'Decimal' || question.fieldType == 'Integer' || question.fieldType == 'Number'){
						question.response.ValueNumber__c = 10;
					}else if(question.fieldType == 'Email'){
						question.response.ValueEmail__c = 'abctest123@example.com';
					}else if(question.fieldType == 'TextEncrypted'){
						question.response.ValueTextEncrypted__c = '111111111';
					}else if(question.fieldType == 'MultiPicklist'){
						question.multiPicklistValues = new List<String>();
						if(question.options != null && question.options.size()>0){
							for(SelectOption so : question.options){
								question.multiPicklistValues.add(so.getValue());
							}
						}
					}else if(question.fieldType == 'Percent'){
						question.response.ValuePercent__c = 0.50;
					}else if(question.fieldType == 'Phone'){
						question.response.ValuePhone__c = '2121231234';
					}else if(question.fieldType == 'Picklist' || question.fieldType == 'Reference'){
						question.response.ValueText__c = 'Domestic';
						if(question.options != null && question.options.size()>0){
							question.response.ValueText__c = question.options[0].getValue();
						}
						if(question.options != null && question.options.size()>1){
							question.response.ValueText__c = question.options[1].getValue();
						}
					}else if(question.fieldType == 'Text'){
						question.response.ValueText__c = 'test text';
					}else if(question.fieldType == 'TextArea'){
						question.response.ValueTextArea__c = 'test text area';
					}else if(question.fieldType == 'LongTextArea'){
						question.response.ValueLongTextArea__c = 'test text area';
					}else if(question.fieldType == 'TextArea'){
						question.response.ValueURL__c = 'http://example.com';
					}
				}
				if(question.fieldName == 'Intended_Program__c'){
					question.response.ValueText__c = String.valueOf(ap.Id);
				}
				if(question.fieldName == 'Intended_Term_of_Entry__c'){
					question.response.ValueText__c = String.valueOf(at.Id);
				}
				if(String.isBlank(question.fieldName)){
					question.response.ValueText__c = 'Test';
				}
				if(question.fieldName == 'Educational_Background__c'){
					question.response.ValueText__c = 'Freshman';
				}
			}
			if(aqg.relatedObject == true && aqg.item != null){
				aqg.newRow();
				for(ApplicationQuestionGroup.SObjectWrapper sObjW : aqg.relatedObjects){
					sObjW.obj.put('School__c',acc.Id);
					sObjW.checkValid();
				}
			}
		}

		PageReference retPR = ac.submit();
	}
	public static TestMethod void testLookupSearch(){
		List<SObject> results = ApplicationRegistration.lookupSearch('Account',null,'Test');
		System.assertEquals(1,results.size());
	}
}