src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>Type of applicant this is.</description>
        <label>Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <description>Citizenship of the applicant.</description>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <description>Type of delivery the student prefers.</description>
        <label>Delivery Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <label>Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <description>Type of the student applying.</description>
        <label>Student Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Traditional</fullName>
                </value>
                <value>
                    <fullName>Adult</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Question for a requirement item.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this question is active. If unchecked, this question won&apos;t display on any applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <inlineHelpText>Applicant type(s) this question applies to (applies to all if blank)</inlineHelpText>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <inlineHelpText>Citizenship type(s) this question applies to (applies to all if blank)</inlineHelpText>
        <label>Citizenship</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Citizenship_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Degree_Type__c</fullName>
        <inlineHelpText>Degree type(s) this question applies to (applies to all if blank)</inlineHelpText>
        <label>Degree Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Degree_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <inlineHelpText>Delivery type(s) this question applies to (applies to all if blank)</inlineHelpText>
        <label>Delivery Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Intended Program this question applies to (applies to all if blank)</inlineHelpText>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <inlineHelpText>Residency type this question applies to (applies to all if blank)</inlineHelpText>
        <label>Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/college this question applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <inlineHelpText>Student type(s) this question applies to (applies to all if blank)</inlineHelpText>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <recordTypes>
        <fullName>Static</fullName>
        <active>true</active>
        <label>Static</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if the requirement is active. If unchecked, this requirement will not display on any applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <inlineHelpText>Applicant type(s) that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <inlineHelpText>Citizenship type(s) that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Citizenship</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Citizenship_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Degree_Type__c</fullName>
        <inlineHelpText>Degree type(s) that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Degree Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Degree_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <inlineHelpText>Delivery type(s) that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Delivery Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Intended program that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <inlineHelpText>Residency type that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/College that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <inlineHelpText>Student type(s) that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Requirement_Item__c.object
<CustomObject>
    <description>An item that&apos;s part of an admissions requirement.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked if this requirement item is active. If unchecked, it will not display on any applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <inlineHelpText>Applicant type(s) that this requirement item applies to (applies to all if blank)</inlineHelpText>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <inlineHelpText>Citizenship type(s) that this requirement item applies to (applies to all if blank)</inlineHelpText>
        <label>Citizenship</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Citizenship_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Degree_Type__c</fullName>
        <inlineHelpText>Degree type(s) that this requirement item applies to (applies to all if blank)</inlineHelpText>
        <label>Degree Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Degree_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <inlineHelpText>Delivery type(s) that this requirement item applies to (applies to all if blank)</inlineHelpText>
        <label>Delivery Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Intended Program that this requirement item applies to (applies to all if blank)</inlineHelpText>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Requirement Items</relationshipLabel>
        <relationshipName>Requirement_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <inlineHelpText>Requirement that this item is a part of</inlineHelpText>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Requirement Items</relationshipLabel>
        <relationshipName>Requirement_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Residency__c</fullName>
        <inlineHelpText>Residency type that this requirement item applies to (applies to all if blank)</inlineHelpText>
        <label>Residency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Residency_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>School_College__c</fullName>
        <inlineHelpText>School/College that this requirement item applies to (applies to all if blank)</inlineHelpText>
        <label>School / College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>School_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <inlineHelpText>Student type(s) that this requirement item applies to (applies to all if blank)</inlineHelpText>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Requirement Item</label>
    <nameField>
        <label>Requirement Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Applicant_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <description>Types of an applicant.</description>
    <masterLabel>Applicant Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Citizenship_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <customValue>
        <fullName>U.S. Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>U.S. Dual Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>U.S. Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Asylee/Refugee</fullName>
    </customValue>
    <customValue>
        <fullName>Domestic</fullName>
        <isActive>false</isActive>
        <label>Domestic</label>
    </customValue>
    <description>Citizenship types for admissions.</description>
    <masterLabel>Citizenship Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Degree_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Associate</fullName>
    </customValue>
    <customValue>
        <fullName>Bachelor&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Master&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Doctoral</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Education Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Juris Doctor (JD)</fullName>
    </customValue>
    <customValue>
        <fullName>Licensure</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Degree</fullName>
    </customValue>
    <customValue>
        <fullName>Post-Masters Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Professional Program</fullName>
    </customValue>
    <description>Types of a degree.</description>
    <masterLabel>Degree Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Delivery_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>On-Campus</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Evenings and Weekends</fullName>
    </customValue>
    <description>Types that a program can be delivered.</description>
    <masterLabel>Delivery Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Residency_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Resident</fullName>
    </customValue>
    <description>Residency types for admissions applications.</description>
    <masterLabel>Residency Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/School_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>College of Arts and Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>College of Health Professions</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <customValue>
        <fullName>School of Business</fullName>
    </customValue>
    <customValue>
        <fullName>School of Education</fullName>
    </customValue>
    <masterLabel>School / College</masterLabel>
</GlobalValueSet>

src/globalValueSets/Student_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Traditional</fullName>
    </customValue>
    <customValue>
        <fullName>Adult</fullName>
    </customValue>
    <description>Student types for admissions.</description>
    <masterLabel>Student Types</masterLabel>
</GlobalValueSet>

src/classes/ApplicationFilter.cls
/*******************************************************************************
@description This controller is used to filter a generic object, requirements, requirement items and questions against the application
@author Huron Consulting Group

Revision (s): 
*******************************************************************************/
public class ApplicationFilter {

    public static Boolean filter(Application__c app, Requirement__c req) {
        return filter(app, req.Active__c,req.Intended_Program__c, req.Applicant_Type__c, req.Citizenship__c, req.Degree_Type__c, req.Delivery_Type__c, req.Residency__c, req.School_College__c, req.Student_Type__c, req.Application_Status__c);
    }

    public static Boolean filter(Application__c app, Requirement_Item__c item) {
        return filter(app, item.Active__c,item.Intended_Program__c, item.Applicant_Type__c, item.Citizenship__c, item.Degree_Type__c, item.Delivery_Type__c, item.Residency__c, item.School_College__c, item.Student_Type__c, item.Application_Status__c);
    }

    public static Boolean filter(Application__c app, Question__c question) {
        return filter(app, question.Active__c,question.Intended_Program__c, question.Applicant_Type__c, question.Citizenship__c, question.Degree_Type__c, question.Delivery_Type__c, question.Residency__c, question.School_College__c, question.Student_Type__c, question.Application_Status__c);
    }

    public static Boolean filter(Application__c app, SObject obj, Boolean checkStatus) {
        Map<String,Object> objFields = obj.getSObjectType().getDescribe().fields.getMap();
        Boolean active = objFields.containsKey('active__c')?(Boolean)obj.get('active__c'):true;
        Id programId = objFields.containsKey('intended_program__c')?String.valueOf(obj.get('intended_program__c')):null;
        String applicantTypes = objFields.containsKey('applicant_type__c')?String.valueOf(obj.get('applicant_type__c')):null;
        String citizenship = objFields.containsKey('citizenship__c')?String.valueOf(obj.get('citizenship__c')):null;
        String degreeType = objFields.containsKey('degree_type__c')?String.valueOf(obj.get('degree_type__c')):null;
        String deliveryType = objFields.containsKey('delivery_type__c')?String.valueOf(obj.get('delivery_type__c')):null;
        String residency = objFields.containsKey('residency__c')?String.valueOf(obj.get('residency__c')):null;
        String schoolCollege = objFields.containsKey('school_college__c')?String.valueOf(obj.get('school_college__c')):null;
        String studentType = objFields.containsKey('student_type__c')?String.valueOf(obj.get('student_type__c')):null;
        String appStatus = (checkStatus == true && objFields.containsKey('application_status__c'))?String.valueOf(obj.get('application_status__c')):null;
        return filter(app, active, programId, applicantTypes, citizenship, degreeType, deliveryType, residency, schoolCollege, studentType, appStatus);
    }

    private static Boolean filter(Application__c app, Boolean active, Id programId, String applicantTypes, String citizenship, String degreeTypes, String deliveryTypes, String residency, String schoolCollege, String studentTypes, String appStatuses) {
        if (app == null)
            return true;
        if (active == false){
            return false;
        }
        if (programId != null && (app.Intended_Program__c == null || app.Intended_Program__c != programId))
            return false;

        if (String.isNotBlank(applicantTypes) && (String.isBlank(app.Applicant_Type__c) || !(new Set<String>(applicantTypes.split(';'))).contains(app.Applicant_Type__c)))
            return false;

        if (String.isNotBlank(citizenship) && (String.isBlank(app.Citizenship__c) || !citizenship.equals(app.Citizenship__c)))
            return false;

        if (String.isNotBlank(schoolCollege) && (String.isBlank(app.School_College__c) || !schoolCollege.equals(app.School_College__c)))
            return false;

        if (String.isNotBlank(deliveryTypes) && (String.isBlank(app.Delivery_Type__c) || !(new Set<String>(deliveryTypes.split(';'))).contains(app.Delivery_Type__c)))
            return false;

        if (String.isNotBlank(residency) && (String.isBlank(app.Residency__c) || !citizenship.equals(app.Residency__c)))
            return false;

        if (String.isNotBlank(studentTypes) && (String.isBlank(app.Student_Type__c) || !(new Set<String>(studentTypes.split(';'))).contains(app.Student_Type__c)))
            return false;
        if(UserInfo.getUserType() != 'Standard' && String.isNotBlank(appStatuses) && (String.isBlank(app.Application_Status__c) || !(new Set<String>(appStatuses.split(';'))).contains(app.Application_Status__c)))
            return false;
        return true;
    }
}