src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>Type of applicant this is.</description>
        <label>Applicant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Control__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Control</label>
        <referenceTo>Application_Control__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <description>Citizenship of the applicant.</description>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <description>Type of delivery the student prefers.</description>
        <label>Delivery Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <description>Type of the student applying.</description>
        <label>Student Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Traditional</fullName>
                </value>
                <value>
                    <fullName>Adult</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Control__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this Application Control is currently active for applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Cancel_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Cancel&quot; button shows-up for.</inlineHelpText>
        <label>Allow Cancel From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Allow_Submit_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Submit&quot; button shows-up for.</inlineHelpText>
        <label>Allow Submit From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Allow_Withdraw_From__c</fullName>
        <inlineHelpText>Application status(es) that the &quot;Withdraw&quot; button shows-up for.</inlineHelpText>
        <label>Allow Withdraw From</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Start_Status__c</fullName>
        <inlineHelpText>Application status that new applications are set to.</inlineHelpText>
        <label>Application Start Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancel_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Cancel&quot; button sets an application to</inlineHelpText>
        <label>Cancel Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this is the default Application Control when no URL Parameter is specified</inlineHelpText>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submit_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Submit&quot; button sets an application to</inlineHelpText>
        <label>Submit Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL_Parameter__c</fullName>
        <inlineHelpText>Text to be included at the end of a link to reference this Application Control. Format is &quot;?at=[URL_PARAMETER]&quot;</inlineHelpText>
        <label>URL Parameter</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Withdraw_Status__c</fullName>
        <inlineHelpText>Application status that the &quot;Withdraw&quot; button sets an application to</inlineHelpText>
        <label>Withdraw Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Application Control</label>
    <nameField>
        <label>Application Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked if this program is currently active. Unchecked otherwise.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <inlineHelpText>Applicant type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <inlineHelpText>Citizenship type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Citizenship_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Degree_Type__c</fullName>
        <inlineHelpText>Degree type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Degree Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Degree_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <inlineHelpText>Delivery type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Delivery Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <inlineHelpText>Student type(s) this program applies to (applies to all if blank)</inlineHelpText>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if the requirement is active. If unchecked, this requirement will not display on any applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <inlineHelpText>Applicant type(s) that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Applicant Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Applicant_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Control__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Application Control that this requirement is a part of</inlineHelpText>
        <label>Application Control</label>
        <referenceTo>Application_Control__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <inlineHelpText>Application status(es) that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Application Status</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <inlineHelpText>Citizenship type(s) that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Citizenship</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Citizenship_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Degree_Type__c</fullName>
        <inlineHelpText>Degree type(s) that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Degree Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Degree_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <inlineHelpText>Delivery type(s) that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Delivery Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Delivery_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Intended_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Intended program that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Intended Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Type__c</fullName>
        <inlineHelpText>Student type(s) that this requirement applies to (applies to all if blank)</inlineHelpText>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Student_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL_Parameter__c</fullName>
        <formula>Application_Control__r.URL_Parameter__c</formula>
        <label>URL Parameter</label>
        <type>Text</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Applicant_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Freshman</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate</fullName>
    </customValue>
    <description>Types of an applicant.</description>
    <masterLabel>Applicant Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Citizenship_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <customValue>
        <fullName>U.S. Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>U.S. Dual Citizen</fullName>
    </customValue>
    <customValue>
        <fullName>U.S. Permanent Resident</fullName>
    </customValue>
    <customValue>
        <fullName>Asylee/Refugee</fullName>
    </customValue>
    <customValue>
        <fullName>Domestic</fullName>
        <isActive>false</isActive>
        <label>Domestic</label>
    </customValue>
    <description>Citizenship types for admissions.</description>
    <masterLabel>Citizenship Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Degree_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Associate</fullName>
    </customValue>
    <customValue>
        <fullName>Bachelor&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Master&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Doctoral</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Education Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Juris Doctor (JD)</fullName>
    </customValue>
    <customValue>
        <fullName>Licensure</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Degree</fullName>
    </customValue>
    <customValue>
        <fullName>Post-Masters Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-Professional Program</fullName>
    </customValue>
    <description>Types of a degree.</description>
    <masterLabel>Degree Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Delivery_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>On-Campus</fullName>
    </customValue>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Evenings and Weekends</fullName>
    </customValue>
    <description>Types that a program can be delivered.</description>
    <masterLabel>Delivery Types</masterLabel>
</GlobalValueSet>

src/globalValueSets/Student_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Traditional</fullName>
    </customValue>
    <customValue>
        <fullName>Adult</fullName>
    </customValue>
    <description>Student types for admissions.</description>
    <masterLabel>Student Types</masterLabel>
</GlobalValueSet>

src/classes/ApplicationFilterTest.cls
@isTest
public class ApplicationFilterTest {
	@testSetup
	public static void testSetup(){
        Application_Control__c appControl = new Application_Control__c(
            Application_Start_Status__c=Application_Control__c.Application_Start_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Active__c=true,
            Allow_Cancel_From__c=Application_Control__c.Allow_Cancel_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Allow_Withdraw_From__c=Application_Control__c.Allow_Withdraw_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Allow_Submit_From__c=Application_Control__c.Allow_Submit_From__c.getDescribe().getPicklistValues()[0].getValue(),
            Cancel_Status__c=Application_Control__c.Cancel_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Default__c=true,
            URL_Parameter__c ='st',
            Submit_Status__c=Application_Control__c.Submit_Status__c.getDescribe().getPicklistValues()[0].getValue(),
            Withdraw_Status__c=Application_Control__c.Withdraw_Status__c.getDescribe().getPicklistValues()[0].getValue()
        );
        insert appControl;
        
		Contact student = new Contact(LastName='TestStudent');
		insert student;
		Program__c ap = new Program__c();
		insert ap;
	}
	public static TestMethod void appFilter1(){
		Contact student = [Select Id from Contact];
		Application__c app = new Application__c(Contact__c=student.Id);
		insert app;
		Program__c ap = [Select Id from Program__c];
		Requirement__c req = new Requirement__c(Name='Test',Intended_Program__c=ap.Id,Applicant_Type__c='Graduate',Application_Control__c=[Select Id from Application_Control__c limit 1].Id);
		insert req;
		//Null App
		System.assertEquals(true,ApplicationFilter.filter(null,req));
		//Req is not active
		System.assertEquals(false,ApplicationFilter.filter(app,req));
		req.Active__c = true;
		update req;
		//App does not have program
		System.assertEquals(false,ApplicationFilter.filter(app,req));
		Test.startTest();
		app.Intended_Program__c = ap.Id;
		update app;
		Test.stopTest();
		//App does not have applicantTypes
		System.assertEquals(false,ApplicationFilter.filter(app,req));
	}
	public static TestMethod void appFilter2(){
		Contact student = [Select Id from Contact];
		Application__c app = new Application__c(Contact__c = student.Id,Applicant_Type__c='Graduate');
		insert app;
		Requirement__c req = new Requirement__c(Active__c=true,Name='Test',Citizenship__c='Domestic',Degree_Type__c='Associate',Application_Control__c=[Select Id from Application_Control__c limit 1].Id);
		insert req;
		//App does not have citizenship
		System.assertEquals(false,ApplicationFilter.filter(app,req));
		Test.startTest();
		app.Citizenship__c = 'Domestic';
		update app;
		Test.stopTest();
	}
	public static TestMethod void appFilter3(){
		Contact student = [Select Id from Contact];
		Program__c ap = [Select Id from Program__c];
		Application__c app = new Application__c(Contact__c = student.Id,Applicant_Type__c='Graduate',Citizenship__c = 'Domestic');
		insert app;
		Requirement__c req = new Requirement__c(Active__c=true,Name='Test',Delivery_Type__c='Online', Student_Type__c='Traditional',Application_Status__c=Requirement__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue(),Application_Control__c=[Select Id from Application_Control__c limit 1].Id);
		insert req;
		//App does not have deliverytype
		System.assertEquals(false,ApplicationFilter.filter(app,req));
		app.Delivery_Type__c = 'Online';
		update app;
		System.assertEquals(false,ApplicationFilter.filter(app,req));
		req.Intended_Program__c = null;
		update req;
		//App does not have Student type
		System.assertEquals(false,ApplicationFilter.filter(app,req));
		Test.startTest();
			app.Student_Type__c = 'Traditional';
			update app;
		Test.stopTest();
		//App does not have appStatuses but we're internal
		System.assertEquals(true,ApplicationFilter.filter(app,req));
	}
	public static TestMethod void appFilter4(){
		Contact student = [Select Id from Contact];
		Application__c app = new Application__c(Contact__c = student.Id,Applicant_Type__c='Graduate',Citizenship__c = 'Domestic',Delivery_Type__c='Online', Student_Type__c='Traditional',Application_Status__c=Requirement__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue());
		insert app;
		Requirement__c req = new Requirement__c(Active__c=true,Name='Test',Application_Control__c=[Select Id from Application_Control__c limit 1].Id);
		insert req;
		System.assertEquals(true,ApplicationFilter.filter(app,req));

	}
	public static TestMethod void appFilter5(){
		Contact student = [Select Id from Contact];
		Application__c app = new Application__c(Contact__c = student.Id,Applicant_Type__c='Graduate',Citizenship__c = 'Domestic',Delivery_Type__c='Online', Student_Type__c='Traditional',Application_Status__c=Requirement__c.Application_Status__c.getDescribe().getPicklistValues()[0].getValue());
		insert app;
		Program__c ip = new Program__c(Active__c=true,Name='Test');
		insert ip;
		System.assertEquals(true,ApplicationFilter.filter(app,ip,false));

	}
}