src/objects/Application_Control__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this Application Control is currently active for applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Control</label>
    <nameField>
        <label>Application Control Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Question for a requirement item.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this question is active. If unchecked, this question won&apos;t display on any applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <inlineHelpText>Order this question is displayed relative to other questions</inlineHelpText>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lookup_Object__c</fullName>
        <inlineHelpText>Object that this field is a part of (used for Related Object Requirement Items)</inlineHelpText>
        <label>Lookup Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Reference_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this field is a part of a newly-created record to reference (e.g. new company that doesn&apos;t already exist in Salesforce)</inlineHelpText>
        <label>New Reference Field</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Picklist_Values__c</fullName>
        <inlineHelpText>List of picklist values, separated by new line</inlineHelpText>
        <label>Picklist Values</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_Object_Field__c</fullName>
        <inlineHelpText>API name of the field on the related object</inlineHelpText>
        <label>Related Object Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requirement_Item__c</fullName>
        <inlineHelpText>Requirement item for this question</inlineHelpText>
        <label>Requirement Item</label>
        <referenceTo>Requirement_Item__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Static_Text__c</fullName>
        <inlineHelpText>Text to display as part of this question</inlineHelpText>
        <label>Static Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <recordTypes>
        <fullName>MultiPicklist</fullName>
        <active>true</active>
        <description>Picklist (Multi-Select)</description>
        <label>Picklist (Multi-Select)</label>
    </recordTypes>
    <recordTypes>
        <fullName>Picklist</fullName>
        <active>true</active>
        <description>Picklist</description>
        <label>Picklist</label>
    </recordTypes>
    <recordTypes>
        <fullName>Radio</fullName>
        <active>true</active>
        <description>Radio field</description>
        <label>Radio</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reference</fullName>
        <active>true</active>
        <label>Reference</label>
    </recordTypes>
    <recordTypes>
        <fullName>Static</fullName>
        <active>true</active>
        <label>Static</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Related_Object_Review__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Related Object Review</label>
</CustomObject>

src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if the requirement is active. If unchecked, this requirement will not display on any applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application_Control__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Application Control that this requirement is a part of</inlineHelpText>
        <label>Application Control</label>
        <referenceTo>Application_Control__c</referenceTo>
        <relationshipLabel>Requirements</relationshipLabel>
        <relationshipName>Requirements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <inlineHelpText>Order this requirement is displayed relative to other requirements</inlineHelpText>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Requirement_Item__c.object
<CustomObject>
    <description>An item that&apos;s part of an admissions requirement.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Checked if this requirement item is active. If unchecked, it will not display on any applications.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <inlineHelpText>Order this requirement item is displayed relative to other requirement items</inlineHelpText>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_List_Object__c</fullName>
        <inlineHelpText>Object that this related object requirement item is populating</inlineHelpText>
        <label>Related List Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Education_History__c</fullName>
                </value>
                <value>
                    <fullName>Employment_History__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <inlineHelpText>Requirement that this item is a part of</inlineHelpText>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Requirement Items</relationshipLabel>
        <relationshipName>Requirement_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement Item</label>
    <nameField>
        <label>Requirement Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RelatedObjectReview.cls
/*******************************************************************************
@description This class allows an administrator to review any related object such as Schools or employers that were not found in the system and approve new records/lookup existing records
@author Huron Consulting Group

Revision (s):
*******************************************************************************/
public class RelatedObjectReview {
	public Map<String, List<SObjectWrapper>> objWrappers{get;set;}
	public Map<String,Set<String>> objFieldMap{get;set;}
	public Map<String,String> objReferenceFieldMap{get;set;}

	public String createNewRecordId{get;set;}
	public String createNewRecordType{get;set;}

	public Application_Control__c appControl{
        get{
            if(appControl == null){
                appControl = ApplicationUtilities.getApplicationControls(ApexPages.currentPage().getParameters().get('at'));
            }
            return appControl;
        }set;
    }
	public RelatedObjectReview() {
		objWrappers = new Map<String, List<SObjectWrapper>>();
		objFieldMap = new Map<String, Set<String>>();
		objReferenceFieldMap = new Map<String,String>();
		Map<String,Set<String>> reqItemFieldMap = new Map<String,Set<String>>();
		Map<String,String> reqItemLookupObjMap = new Map<String,String>();
		Map<String,String> reqItemRelatedObjMap = new Map<String,String>();
		//Find all relevant fields based on questions asked
		for(Question__c q : [SELECT Id, Lookup_Object__c, Related_Object_Field__c, Requirement_Item__c, Requirement_Item__r.Related_List_Object__c, RecordType.DeveloperName, New_Reference_Field__c ,Static_Text__c FROM Question__c WHERE (Lookup_Object__c != null OR New_Reference_Field__c = true) AND Active__c = :true AND Requirement_Item__r.Active__c = :true AND Requirement_Item__r.Requirement__r.Active__c = :true AND Requirement_Item__r.Requirement__r.Application_Control__c = :appControl.Id ORDER BY New_Reference_Field__c, Display_Order__c ASC NULLS LAST]){
			if(q.New_Reference_Field__c == false && q.RecordType.DeveloperName == 'Reference' && String.isNotBlank(q.Lookup_Object__c)){
				reqItemLookupObjMap.put(q.Requirement_Item__c,q.Lookup_Object__c);
				reqItemRelatedObjMap.put(q.Requirement_Item__r.Related_List_Object__c,q.Lookup_Object__c);
				if(!objFieldMap.containsKey(q.Lookup_Object__c)){
					objFieldMap.put(q.Lookup_Object__c,new Set<String>());
				}
				if(reqItemFieldMap.containsKey(q.Requirement_Item__c)){
					objFieldMap.get(q.Lookup_Object__c).addAll(reqItemFieldMap.get(q.Requirement_Item__c));
					reqItemFieldMap.remove(q.Requirement_Item__c);
				}
				objReferenceFieldMap.put(q.Requirement_Item__r.Related_List_Object__c,q.Related_Object_Field__c);
			}else if(q.New_Reference_Field__c == true){
				if(reqItemLookupObjMap.containsKey(q.Requirement_Item__c)){
					objFieldMap.get(reqItemLookupObjMap.get(q.Requirement_Item__c)).add(q.Related_Object_Field__c);
				}else{
					if(!reqItemFieldMap.containsKey(q.Requirement_Item__c)){
						reqItemFieldMap.put(q.Requirement_Item__c,new Set<String>());
					}
					reqItemFieldMap.get(q.Requirement_Item__c).add(q.Related_Object_Field__c);
				}
			}
		}
		Set<String> reviewObjs = Related_Object_Review__c.getAll().keySet();
		for(String s : reviewObjs){
			if(reqItemRelatedObjMap.containsKey(s)){
				String query = 'Select Id, Related_Object_JSON__c FROM ' + s + ' WHERE Holding_Name__c != null';
				if(!objWrappers.containsKey(reqItemRelatedObjMap.get(s))){
					objWrappers.put(reqItemRelatedObjMap.get(s),new List<SObjectWrapper>());
				}
				objWrappers.get(reqItemRelatedObjMap.get(s)).addAll(convertList(database.query(query),reqItemRelatedObjMap.get(s)));
			}
		}
	}
	/*******************************************************************************
    * @description Creates a new record based on the JSON record + updates by the administrator
    ********************************************************************************/
	public void createRec(){
		if(objWrappers.containsKey(createNewRecordType)){

			for(Integer i = 0;i<objWrappers.get(createNewRecordType).size();i++){
				SObjectWrapper obj = objWrappers.get(createNewRecordType)[i];
				if(obj.obj.Id == createNewRecordId){
					objWrappers.get(createNewRecordType).remove(i);
					insert obj.relatedSObj;
					obj.obj.put(objReferenceFieldMap.get(obj.obj.getSObjectType().getDescribe().getName()),obj.relatedSObj.Id);
					obj.obj.put('Holding_Name__c',null);
					obj.obj.put('Related_Object_JSON__c',null);
					update obj.obj;
					break;
				}
			}
		}
		createNewRecordType = null;
		createNewRecordId = null;
	}
	/*******************************************************************************
    * @description Saves the entire table. If the administrator had linked an existing record, the record is removed from the table, and its JSON is cleared
    ********************************************************************************/
	public void saveTable(){
		List<SObject> objsToUpdate = new List<SObject>();
		if(objWrappers.containsKey(createNewRecordType)){
			for(Integer i = 0;i<objWrappers.get(createNewRecordType).size();i++){
				SObjectWrapper obj = objWrappers.get(createNewRecordType)[i];
				if(String.isNotBlank(obj.existingRecord)){
					objWrappers.get(createNewRecordType).remove(i);
					obj.obj.put(objReferenceFieldMap.get(obj.obj.getSObjectType().getDescribe().getName()),obj.existingRecord);
					obj.obj.put('Holding_Name__c',null);
					obj.obj.put('Related_Object_JSON__c',null);
				}else{
					obj.obj.put('Related_Object_JSON__c', JSON.serialize(obj.relatedSObj));
				}
				objsToUpdate.add(obj.obj);
			}
		}
		if(objsToUpdate.size()>0){
			update objsToUpdate;
		}
		createNewRecordType = null;
	}

	/*******************************************************************************
    * @description Converts a list of sObjects to a wrapper for ease of use
    ********************************************************************************/
	public List<SObjectWrapper> convertList(List<SObject> objList, String typeToConvert){
		List<SObjectWrapper> retLst = new List<SObjectWrapper>();
		for(SObject obj : objList){
			if(String.isNotBlank((String)obj.get('Related_Object_JSON__c'))){
				retLst.add(new SObjectWrapper(obj,this,typeToConvert));
			}
		}
		return retLst;
	}
	/*******************************************************************************
    * @description Allows the administrator to lookup existing records to tie to.
    ********************************************************************************/
	@RemoteAction
    public static List<SObject> lookupSearch(String sObj, String sObjFilter, String term){

        return new ActionWithSharing().lookupSearchWithSharing(sObj,sObjFilter, term);
    }
    public with sharing class ActionWithSharing{
        public List<SObject> lookupSearchWithSharing(String sObj, String sObjFilter, String term){
            if(Schema.getGlobalDescribe().get(sObj).getDescribe().isAccessible()){
                String query = 'Select Id, Name FROM '+sObj+' WHERE Name like \'%'+String.escapeSingleQuotes(term)+'%\'';
                if(String.isNotBlank(sObjFilter)){
                    query += ' AND ' + sObjFilter;
                }
                query += ' ORDER BY Name ASC';
                try{
                    return database.query(query);
                }catch(Exception e){
                    return new List<SObject>();
                }
            }
            return new List<SObject>();
        }
    }
	public class SObjectWrapper{
		public SObject obj{get;set;}
		public SObject relatedSObj{get;set;}
		public Map<String,ApplicationQuestion> relatedObjMap{get;set;}
		private RelatedObjectReview cls;
		public String fieldKeys{get;set;}
		public String existingRecord{get;set;}
		public SObjectWrapper(SObject obj, RelatedObjectReview cls, String typeOfRecord){
			this.obj = obj;
			this.cls = cls;
			Map<String, Object> cObjMap = (Map<String, Object>) JSON.deserializeUntyped((String)obj.get('Related_Object_JSON__c'));
			relatedSObj = (SObject)JSON.deserialize(JSON.serialize(cObjMap), Sobject.class);
			relatedObjMap = new Map<String,ApplicationQuestion>();
			Map<String,Object> fieldMap = relatedSObj.getPopulatedFieldsAsMap();
			for(String s : cls.objFieldMap.get(typeOfRecord)){
				Question__c q = new Question__c(New_Reference_Field__c=true,Related_Object_Field__c=s,RecordType=new RecordType(DeveloperName=ApplicationQuestion.fieldTypes.get(relatedSObj.getSObjectType().getDescribe().fields.getMap().get(s.toLowerCase()).getDescribe().getType())));
				if(q.RecordType.DeveloperName == 'Picklist' || q.RecordType.DeveloperName == 'MultiPicklist' || q.RecordType.DeveloperName == 'Radio'){
					List<String> options = new List<String>();
					for(PicklistEntry ple : relatedSObj.getSObjectType().getDescribe().fields.getMap().get(s).getDescribe().getPicklistValues()){
						options.add(ple.getValue());
					}
					q.Picklist_Values__c = String.join(options,'\n');
				}
				relatedObjMap.put(s,new ApplicationQuestion(relatedSObj,q,null));
			}
			fieldKeys = '';
			for(String s : relatedObjMap.keySet()){
				fieldKeys += s + ',';
			}
		}
	}
}