src/objects/Requirement_Item__c.object
<CustomObject>
    <description>An item that&apos;s part of an admissions requirement.</description>
    <fields>
        <fullName>Internal_Only_Show_on_Checklist__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this requirement item will show on the checklist even if it&apos;s internal-only. The applicant will not be able to view answers for this requirement item, but will be able to see if it&apos;s been satisfied or not.</description>
        <inlineHelpText>If checked, this requirement item will show on the checklist even if it&apos;s internal-only. The applicant will not be able to view answers for this requirement item, but will be able to see if it&apos;s been satisfied or not.</inlineHelpText>
        <label>Internal Only Show on Checklist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this requirement item can only be fulfilled by an internal user.</inlineHelpText>
        <label>Internal Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Requirement_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this requirement item is being asked to an external user (e.g. a recommender), this field looks-up to the corresponding internal requirement item that the applicant fulfills (e.g. recommender name and email)</inlineHelpText>
        <label>Internal Requirement Item</label>
        <referenceTo>Requirement_Item__c</referenceTo>
        <relationshipLabel>External Requirement Items</relationshipLabel>
        <relationshipName>External_Requirement_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requirement Item</label>
    <nameField>
        <label>Requirement Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RequirementItemWrapper.cls
public class RequirementItemWrapper {

    public Requirement_Item__c reqItem{get;set;}
    public Boolean reqItemStatus{get;set;}
    public Boolean display {
        get {
            return ((!reqItem.Internal_Only__c || reqItem.Internal_Only_Show_on_Checklist__c) && reqItem.Internal_Requirement_Item__c == null) || UserInfo.getUserType().equals('Standard');
        }
    }
    public RequirementItemWrapper(Requirement_Item__c reqItem){
        this.reqItem = reqItem;
        this.reqItemStatus = false;
    }   
    
}