src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Internal_Only_Show_on_Checklist__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this requirement will show on the checklist even if it&apos;s internal-only. The applicant will not be able to view answers for this requirement, but will be able to see if it&apos;s been satisfied or not.</description>
        <inlineHelpText>If checked, this requirement will show on the checklist even if it&apos;s internal-only. The applicant will not be able to view answers for this requirement, but will be able to see if it&apos;s been satisfied or not.</inlineHelpText>
        <label>Internal Only Show on Checklist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this requirement can only be fulfilled by an internal user</inlineHelpText>
        <label>Internal Only</label>
        <type>Checkbox</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RequirementWrapper.cls
public class RequirementWrapper {

        public Requirement__c req{get;set;}
        public Boolean reqStatus{get;set;}
        public Boolean viewed{get;set;}
        public Boolean display {
            get {
                return !req.Internal_Only__c || req.Internal_Only_Show_on_Checklist__c || UserInfo.getUserType().equals('Standard');
            }
        }
        public Map<Id,RequirementItemWrapper> reqItemMap{get;set;}
        public List<RequirementItemWrapper> reqItems{
            get{
                return reqItemMap.values();
            }
        }
        public RequirementWrapper(Requirement__c req){
            this.req = req;
            this.reqStatus = false;
            this.viewed = true;
            this.reqItemMap = new Map<Id,RequirementItemWrapper>();
        }
    
}