src/objects/Requirement__c.object
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <label>Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Requirement_Item__c.object
<CustomObject>
    <description>An item that&apos;s part of an admissions requirement.</description>
    <fields>
        <fullName>Requirement__c</fullName>
        <inlineHelpText>Requirement that this item is a part of</inlineHelpText>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Requirement Items</relationshipLabel>
        <relationshipName>Requirement_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Requirement Item</label>
    <nameField>
        <label>Requirement Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirement Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RequirementWrapperTest.cls
@isTest
private class RequirementWrapperTest {
    
    @isTest
    static void test_requirement_wrapper() {
        
        Requirement__c r = new Requirement__c();
        Requirement_Item__c ri = new Requirement_Item__c();
        
        Test.startTest();
        
        RequirementWrapper rw = new RequirementWrapper(r);
        Boolean display = rw.display;
        List<RequirementItemWrapper> reqItems = rw.reqItems;
        
        RequirementItemWrapper riw = new RequirementItemWrapper(ri);
        Boolean riDisplay = riw.display;
        
        Test.stopTest();
    }
}